Repository ewoo14/CodeBloom, pull requests merged in 2024-11, with the labels that each got.

#3 [Docs] 개발 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/feature-template.md
Labels: documentation

#10 [Feat] QueryDSL 기본 설정
  build.gradle
  src/main/java/com/sparta/project/config/QueryDslConfig.java
Labels: feat

#5 [Feat] 오류 전역 처리 기능
  src/main/java/com/sparta/project/exception/CodeBloomException.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/exception/ExceptionResponse.java
  src/main/java/com/sparta/project/exception/GlobalControllerAdvice.java
Labels: feat

#7 [Feat] entity 생성
  src/main/java/com/sparta/project/ProjectApplication.java
  src/main/java/com/sparta/project/domain/Address.java
  src/main/java/com/sparta/project/domain/Ai.java
  src/main/java/com/sparta/project/domain/BaseEntity.java
  src/main/java/com/sparta/project/domain/Location.java
  src/main/java/com/sparta/project/domain/Menu.java
  src/main/java/com/sparta/project/domain/Order.java
  src/main/java/com/sparta/project/domain/OrderMenu.java
  src/main/java/com/sparta/project/domain/Payment.java
  src/main/java/com/sparta/project/domain/Review.java
  src/main/java/com/sparta/project/domain/Store.java
  src/main/java/com/sparta/project/domain/StoreCategory.java
  src/main/java/com/sparta/project/domain/StoreRequest.java
  src/main/java/com/sparta/project/domain/User.java
  src/main/java/com/sparta/project/domain/enums/OrderStatus.java
  src/main/java/com/sparta/project/domain/enums/OrderType.java
  src/main/java/com/sparta/project/domain/enums/PaymentType.java
  src/main/java/com/sparta/project/domain/enums/PgName.java
  src/main/java/com/sparta/project/domain/enums/Role.java
Labels: feat

#6 [Feat] 도메인별 컨트롤러 초안 작성
  .DS_Store
  src/main/java/com/sparta/project/controller/AIController.java
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/controller/MenuController.java
  src/main/java/com/sparta/project/controller/OrderController.java
  src/main/java/com/sparta/project/controller/PaymentController.java
  src/main/java/com/sparta/project/controller/ReviewController.java
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/controller/StoreController.java
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/controller/UserController.java
Labels: feat

#13 [Fix] Address.streetNumber: Integer -> String
  src/main/java/com/sparta/project/domain/Address.java
Labels: fix

#14 [Feat] 사용자 인증 및 인가를 위한 설정
  build.gradle
  src/main/java/com/sparta/project/config/BCryptPasswordConfig.java
  src/main/java/com/sparta/project/config/SecurityConfig.java
  src/main/java/com/sparta/project/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/sparta/project/config/jwt/JwtUtil.java
  src/main/java/com/sparta/project/config/jwt/JwtValidationType.java
  src/main/java/com/sparta/project/config/jwt/UserDetail.java
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/domain/User.java
  src/main/java/com/sparta/project/dto/common/ApiResponse.java
  src/main/java/com/sparta/project/dto/user/UserLoginRequest.java
  src/main/java/com/sparta/project/dto/user/UserSignupRequest.java
  src/main/java/com/sparta/project/exception/CustomAccessDeniedHandler.java
  src/main/java/com/sparta/project/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/exception/ExceptionResponse.java
  src/main/java/com/sparta/project/repository/UserRepository.java
  src/main/java/com/sparta/project/service/UserService.java
Labels: feat

#16 [Feat] menu 및 AI dto와 service 코드 작성
  .gitignore
  src/main/java/com/sparta/project/config/jwt/RestTemplateConfig.java
  src/main/java/com/sparta/project/controller/AIController.java
  src/main/java/com/sparta/project/controller/MenuController.java
  src/main/java/com/sparta/project/domain/Ai.java
  src/main/java/com/sparta/project/domain/Menu.java
  src/main/java/com/sparta/project/dto/ai/AIRequest.java
  src/main/java/com/sparta/project/dto/ai/AIResponse.java
  src/main/java/com/sparta/project/dto/common/PageResponse.java
  src/main/java/com/sparta/project/dto/menu/MenuCreateRequest.java
  src/main/java/com/sparta/project/dto/menu/MenuResponse.java
  src/main/java/com/sparta/project/dto/menu/MenuUpdateRequest.java
  src/main/java/com/sparta/project/exception/CodeBloomException.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/AIRepository.java
  src/main/java/com/sparta/project/repository/MenuRepository.java
  src/main/java/com/sparta/project/service/AIService.java
  src/main/java/com/sparta/project/service/MenuService.java
Labels: feat

#22 [Feat] 가게 요청 생성 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/domain/StoreRequest.java
  src/main/java/com/sparta/project/domain/enums/StoreRequestStatus.java
  src/main/java/com/sparta/project/dto/storerequest/StoreCreateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/LocationRepository.java
  src/main/java/com/sparta/project/repository/StoreCategoryRepository.java
  src/main/java/com/sparta/project/repository/StoreRequestRepository.java
  src/main/java/com/sparta/project/service/StoreCategoryService.java
  src/main/java/com/sparta/project/service/StoreLocationService.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
  src/main/java/com/sparta/project/service/UserService.java
  src/main/java/com/sparta/project/util/UuidGenerator.java
Labels: feat

#24 [Docs] 더미 데이터 Sql 쿼리 파일 추가
  docs/sql/insert_dummy_data.sql
Labels: feat

#28 [Feat] 배송지 추가 API
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/domain/Address.java
  src/main/java/com/sparta/project/dto/address/AddressCreateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/AddressRepository.java
  src/main/java/com/sparta/project/service/AddressService.java
Labels: feat

#31 [Fix] MenuService 메서드별 테스트 완성
  src/main/java/com/sparta/project/config/RestTemplateConfig.java
  src/main/java/com/sparta/project/controller/AIController.java
  src/main/java/com/sparta/project/controller/MenuController.java
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/initializer/DataInitializer.java
  src/main/java/com/sparta/project/repository/AIRepository.java
  src/main/java/com/sparta/project/repository/StoreRepository.java
  src/main/java/com/sparta/project/service/AIService.java
  src/main/java/com/sparta/project/service/MenuService.java
  src/main/resources/data.sql
Labels: fix

#32 [Feat] 가게 카테고리 생성 API
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/domain/StoreCategory.java
  src/main/java/com/sparta/project/dto/storecategory/StoreCategoryCreateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/StoreCategoryRepository.java
  src/main/java/com/sparta/project/service/StoreCategoryService.java
  src/main/java/com/sparta/project/util/PermissionValidator.java
Labels: feat

#37 [Feat] 가게 요청 승인 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/domain/Store.java
  src/main/java/com/sparta/project/domain/StoreRequest.java
  src/main/java/com/sparta/project/dto/store/StoreCreateData.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
  src/main/java/com/sparta/project/service/StoreService.java
Labels: feat

#39 [Feat] 배송지 수정 API
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/domain/Address.java
  src/main/java/com/sparta/project/dto/address/AddressUpdateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/service/AddressService.java
Labels: feat

#42 [Feat] 가게 카테고리 수정 API
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/domain/StoreCategory.java
  src/main/java/com/sparta/project/dto/storecategory/StoreCategoryUpdateRequest.java
  src/main/java/com/sparta/project/service/StoreCategoryService.java
Labels: feat

#45 [Feat] 배송지 삭제 API
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/service/AddressService.java
Labels: feat

#46 [Feat] 가게 카테고리 삭제 API
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/service/StoreCategoryService.java
Labels: feat

#41 [Feat] location 서비스 및 컨트롤러 작성, Menu 중복 방지 및 기타
  src/main/java/com/sparta/project/controller/AIController.java
  src/main/java/com/sparta/project/controller/LocationController.java
  src/main/java/com/sparta/project/controller/MenuController.java
  src/main/java/com/sparta/project/domain/Ai.java
  src/main/java/com/sparta/project/domain/Location.java
  src/main/java/com/sparta/project/domain/Menu.java
  src/main/java/com/sparta/project/dto/ai/AIRequest.java
  src/main/java/com/sparta/project/dto/location/LocationRequest.java
  src/main/java/com/sparta/project/dto/location/LocationResponse.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/AIRepository.java
  src/main/java/com/sparta/project/repository/LocationRepository.java
  src/main/java/com/sparta/project/repository/MenuRepository.java
  src/main/java/com/sparta/project/service/AIService.java
  src/main/java/com/sparta/project/service/LocationService.java
  src/main/java/com/sparta/project/service/MenuService.java
  src/main/java/com/sparta/project/service/StoreLocationService.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
  src/main/java/com/sparta/project/util/PermissionValidator.java
Labels: feat

#35 [Feat] 음식점 상세조회, 수정, 삭제
  src/main/java/com/sparta/project/config/AuditorAwareImpl.java
  src/main/java/com/sparta/project/controller/StoreController.java
  src/main/java/com/sparta/project/domain/Location.java
  src/main/java/com/sparta/project/domain/Store.java
  src/main/java/com/sparta/project/dto/store/StoreResponse.java
  src/main/java/com/sparta/project/dto/store/StoreUpdateRequest.java
  src/main/java/com/sparta/project/repository/StoreQueryRepository.java
  src/main/java/com/sparta/project/service/OrderService.java
  src/main/java/com/sparta/project/service/PaymentService.java
  src/main/java/com/sparta/project/service/StoreService.java
  src/main/resources/data.sql
  src/test/java/com/sparta/project/ProjectApplicationTests.java
  src/test/java/com/sparta/project/service/StoreServiceTest.java
Labels: feat

#55 [Feat] 배송지 상세 조회 API
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/dto/address/AddressAdminResponse.java
  src/main/java/com/sparta/project/dto/address/AddressResponse.java
  src/main/java/com/sparta/project/service/AddressService.java
Labels: feat

#57 [Feat] 자신의 음식점 목록 조회, 모든 권한을 위한 음식점 목록 조회
  src/main/java/com/sparta/project/controller/StoreController.java
  src/main/java/com/sparta/project/repository/StoreQueryRepository.java
  src/main/java/com/sparta/project/repository/StoreRepository.java
  src/main/java/com/sparta/project/service/StoreService.java
  src/test/java/com/sparta/project/repository/StoreQueryRepositoryTest.java
Labels: feat

#60 [Feat] 음식점 생성 요청 반려 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/domain/StoreRequest.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
Labels: feat

#58 [Feat] 리뷰 생성 및 조회 API 구현
  .DS_Store
  src/main/java/com/sparta/project/controller/AIController.java
  src/main/java/com/sparta/project/controller/LocationController.java
  src/main/java/com/sparta/project/controller/MenuController.java
  src/main/java/com/sparta/project/controller/ReviewController.java
  src/main/java/com/sparta/project/domain/Review.java
  src/main/java/com/sparta/project/dto/menu/MenuCreateRequest.java
  src/main/java/com/sparta/project/dto/review/ReviewCreateRequest.java
  src/main/java/com/sparta/project/dto/review/ReviewResponse.java
  src/main/java/com/sparta/project/dto/review/ReviewUpdateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/ReviewRepository.java
  src/main/java/com/sparta/project/service/LocationService.java
  src/main/java/com/sparta/project/service/MenuService.java
  src/main/java/com/sparta/project/service/ReviewService.java
Labels: feat

#63 [Feat] 유저 삭제 API
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/service/UserService.java
Labels: feat

#67 [Feat] 결제 내역 목록 조회 메서드 3개 구현 및 결제 요청 수정
  src/main/java/com/sparta/project/client/PgClient.java
  src/main/java/com/sparta/project/controller/PaymentController.java
  src/main/java/com/sparta/project/dto/payment/PaymentCreateResponse.java
  src/main/java/com/sparta/project/dto/payment/PaymentRequest.java
  src/main/java/com/sparta/project/dto/payment/PaymentResponse.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/repository/PaymentRepository.java
  src/main/java/com/sparta/project/repository/StoreRepository.java
  src/main/java/com/sparta/project/service/PaymentService.java
  src/test/java/com/sparta/project/service/PaymentServiceTest.java
Labels: feat

#68 [Feat] 주문 상세 조회
  src/main/java/com/sparta/project/controller/OrderController.java
  src/main/java/com/sparta/project/dto/order/OrderResponse.java
  src/main/java/com/sparta/project/service/OrderService.java
Labels: feat

#78 [Feat] 가게 카테고리 상세 조회 API
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/dto/storecategory/StoreCategoryAdminResponse.java
  src/main/java/com/sparta/project/dto/storecategory/StoreCategoryResponse.java
  src/main/java/com/sparta/project/dto/storecategory/StoreCategoryUserResponse.java
  src/main/java/com/sparta/project/service/StoreCategoryService.java
Labels: feat

#81 [Feat] 자신이 요청한 음식점 생성 요청 목록 조회 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/dto/storerequest/StoreRequestUserResponse.java
  src/main/java/com/sparta/project/repository/storerequest/StoreRequestCustomRepository.java
  src/main/java/com/sparta/project/repository/storerequest/StoreRequestCustomRepositoryImpl.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
Labels: feat

#79 [Feat] 전체 유저 목록 조회 API
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/dto/user/UserAdminResponse.java
  src/main/java/com/sparta/project/initializer/DataInitializer.java
  src/main/java/com/sparta/project/repository/user/UserCustomRepository.java
  src/main/java/com/sparta/project/repository/user/UserCustomRepositoryImpl.java
  src/main/java/com/sparta/project/repository/user/UserRepository.java
  src/main/java/com/sparta/project/service/AIService.java
  src/main/java/com/sparta/project/service/ReviewService.java
  src/main/java/com/sparta/project/service/UserService.java
  src/test/java/com/sparta/project/repository/StoreQueryRepositoryTest.java
  src/test/java/com/sparta/project/service/PaymentServiceTest.java
  src/test/java/com/sparta/project/service/StoreServiceTest.java
Labels: feat

#86 [Feat] 유저 상세 조회 API
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/dto/user/UserAdminResponse.java
  src/main/java/com/sparta/project/dto/user/UserBasicResponse.java
  src/main/java/com/sparta/project/dto/user/UserResponse.java
  src/main/java/com/sparta/project/service/UserService.java
Labels: feat

#87 [Feat] 음식점 생성 요청 정보를 수정하는 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/domain/StoreRequest.java
  src/main/java/com/sparta/project/dto/storerequest/StoreRequestUpdateRequest.java
  src/main/java/com/sparta/project/exception/ErrorCode.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
Labels: feat

#89 [Feat] 음식점 생성 요청 상세 조회 API
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/dto/storerequest/StoreRequestAdminResponse.java
  src/main/java/com/sparta/project/dto/storerequest/StoreRequestOwnerResponse.java
  src/main/java/com/sparta/project/dto/storerequest/StoreRequestResponse.java
  src/main/java/com/sparta/project/service/StoreRequestService.java
Labels: feat

#95 [Docs] README.md 작성
  README.md
Labels: documentation

#99 [Feat] 목록 조회 정렬 기준에 수정 일자 추가
  src/main/java/com/sparta/project/controller/AddressController.java
  src/main/java/com/sparta/project/controller/StoreCategoryController.java
  src/main/java/com/sparta/project/controller/StoreRequestController.java
  src/main/java/com/sparta/project/controller/UserController.java
  src/main/java/com/sparta/project/repository/address/AddressCustomRepositoryImpl.java
  src/main/java/com/sparta/project/repository/storecategory/StoreCategoryCustomRepositoryImpl.java
  src/main/java/com/sparta/project/repository/storerequest/StoreRequestCustomRepositoryImpl.java
  src/main/java/com/sparta/project/repository/user/UserCustomRepositoryImpl.java
Labels: feat

#101 [Docs] README API 명세서 링크 추가
  README.md
Labels: documentation
